# Generated by Django 5.0.6 on 2024-06-24 15:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(max_length=100)),
                ("album_name", models.CharField(max_length=100)),
                ("year_of_release", models.PositiveIntegerField()),
                ("ranking", models.IntegerField()),
            ],
        ),
    ]
