# Generated by Django 5.0.6 on 2024-06-24 15:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="album_cover",
            field=models.ImageField(null=True, upload_to="album_covers/"),
        ),
    ]
