# Generated by Django 5.0.6 on 2024-06-24 16:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_album_album_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="ranking",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="album",
            name="year_of_release",
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
