# Generated by Django 5.0.6 on 2024-06-25 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0003_alter_album_ranking_alter_album_year_of_release"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="album_cover",
            field=models.ImageField(blank=True, null=True, upload_to="album_covers/"),
        ),
        migrations.AlterField(
            model_name="album",
            name="ranking",
            field=models.IntegerField(
                default=5,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("duration", models.DurationField()),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="albums.album",
                    ),
                ),
            ],
        ),
    ]
